service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  # profile: femasters
  # region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    cors: true
    events:
      - http: "GET /todos/{todo}"
      - http: "GET /todos"
